import * as THREE from 'three';

export const M = {
  floor: new THREE.MeshLambertMaterial({ color: 0x92704e }),
  floorLine: new THREE.MeshLambertMaterial({ color: 0x584532 }),
  wall: new THREE.MeshLambertMaterial({ color: 0xded3ba }),
  wallAcc: new THREE.MeshLambertMaterial({ color: 0x51695b }),
  desk: new THREE.MeshLambertMaterial({ color: 0xd3c8af }),
  deskTop: new THREE.MeshLambertMaterial({ color: 0x9a6843 }),
  tv: new THREE.MeshLambertMaterial({ color: 0x1a1a22 }),
  tvScreen: new THREE.MeshLambertMaterial({ color: 0x1155aa, emissive: 0x1144cc, emissiveIntensity: 0.8 }),
  bookA: new THREE.MeshLambertMaterial({ color: 0xb56349 }),
  bookB: new THREE.MeshLambertMaterial({ color: 0x426d77 }),
  bookC: new THREE.MeshLambertMaterial({ color: 0x789067 }),
  bookD: new THREE.MeshLambertMaterial({ color: 0xc4a25a }),
  plant: new THREE.MeshLambertMaterial({ color: 0x2d6e3a }),
  pot: new THREE.MeshLambertMaterial({ color: 0xb87957 }),
  laptop: new THREE.MeshStandardMaterial({ color: 0x050505, roughness: 0.9, metalness: 0.1 }),
  lapScreen: new THREE.MeshLambertMaterial({ color: 0x88ff88, emissive: 0x44ff44, emissiveIntensity: 0.5 }),
  chair: new THREE.MeshLambertMaterial({ color: 0x2a1a0a }),
  chairCushion: new THREE.MeshLambertMaterial({ color: 0x3f655b }),
  rug: new THREE.MeshLambertMaterial({ color: 0x436257 }),
  rugAcc: new THREE.MeshLambertMaterial({ color: 0xc7ad7d }),
  shelf: new THREE.MeshLambertMaterial({ color: 0x725237 }),
  poster: new THREE.MeshLambertMaterial({ color: 0x0a1a1a, emissive: 0x003322, emissiveIntensity: 0.3 }),
  lamp: new THREE.MeshLambertMaterial({ color: 0xb89452 }),
  lampShade: new THREE.MeshLambertMaterial({ color: 0xffdd88, emissive: 0xffcc44, emissiveIntensity: 0.6 }),
  pixel: new THREE.MeshLambertMaterial({ color: 0xb8ff8c, emissive: 0x44aa22, emissiveIntensity: 0.4 }),
  white: new THREE.MeshLambertMaterial({ color: 0xfafafa }),
  skin: new THREE.MeshLambertMaterial({ color: 0xe8b87a }),
  hoodie: new THREE.MeshLambertMaterial({ color: 0x3a4050 }),
  pants: new THREE.MeshLambertMaterial({ color: 0x2a2a3a }),
  hair: new THREE.MeshLambertMaterial({ color: 0x1a1a1a }),
  // new peripherals
  keyboard: new THREE.MeshLambertMaterial({ color: 0xf0f0f0 }),
  keycap: new THREE.MeshLambertMaterial({ color: 0xe0e0e0 }),
  mousepad: new THREE.MeshLambertMaterial({ color: 0x2d4944 }),
  mouseMat: new THREE.MeshLambertMaterial({ color: 0xf5f5f5 }),
  piano: new THREE.MeshLambertMaterial({ color: 0x111116 }),
  pianoKeyWhite: new THREE.MeshLambertMaterial({ color: 0xf4f1e8 }),
  pianoKeyBlack: new THREE.MeshLambertMaterial({ color: 0x050505 }),
  windowFrame: new THREE.MeshLambertMaterial({ color: 0xeee0c3 }),
  windowGlass: new THREE.MeshLambertMaterial({ color: 0x73b7f2, transparent: true, opacity: 0.42, emissive: 0x1d5f9f, emissiveIntensity: 0.12 }),
};
