import * as THREE from 'three';

export const M = {
  floor: new THREE.MeshLambertMaterial({ color: 0x2a2018 }),
  floorLine: new THREE.MeshLambertMaterial({ color: 0x352a1e }),
  wall: new THREE.MeshLambertMaterial({ color: 0xe8e0d4 }),
  wallAcc: new THREE.MeshLambertMaterial({ color: 0xd4ccc0 }),
  desk: new THREE.MeshLambertMaterial({ color: 0xf0ece6 }),
  deskTop: new THREE.MeshLambertMaterial({ color: 0xfafafa }),
  tv: new THREE.MeshLambertMaterial({ color: 0x1a1a22 }),
  tvScreen: new THREE.MeshLambertMaterial({ color: 0x1155aa, emissive: 0x1144cc, emissiveIntensity: 0.8 }),
  bookA: new THREE.MeshLambertMaterial({ color: 0xaa3355 }),
  bookB: new THREE.MeshLambertMaterial({ color: 0x3355aa }),
  bookC: new THREE.MeshLambertMaterial({ color: 0x33aa55 }),
  bookD: new THREE.MeshLambertMaterial({ color: 0xaaaa33 }),
  plant: new THREE.MeshLambertMaterial({ color: 0x2d6e3a }),
  pot: new THREE.MeshLambertMaterial({ color: 0x8b4513 }),
  laptop: new THREE.MeshStandardMaterial({ color: 0x050505, roughness: 0.9, metalness: 0.1 }),
  lapScreen: new THREE.MeshLambertMaterial({ color: 0x88ff88, emissive: 0x44ff44, emissiveIntensity: 0.5 }),
  chair: new THREE.MeshLambertMaterial({ color: 0x2a1a0a }),
  chairCushion: new THREE.MeshLambertMaterial({ color: 0x553311 }),
  rug: new THREE.MeshLambertMaterial({ color: 0x3d2050 }),
  rugAcc: new THREE.MeshLambertMaterial({ color: 0x5a3570 }),
  shelf: new THREE.MeshLambertMaterial({ color: 0x3a2a18 }),
  poster: new THREE.MeshLambertMaterial({ color: 0x0a1a1a, emissive: 0x003322, emissiveIntensity: 0.3 }),
  lamp: new THREE.MeshLambertMaterial({ color: 0xccccaa }),
  lampShade: new THREE.MeshLambertMaterial({ color: 0xffdd88, emissive: 0xffcc44, emissiveIntensity: 0.6 }),
  pixel: new THREE.MeshLambertMaterial({ color: 0xb8ff8c, emissive: 0x44aa22, emissiveIntensity: 0.4 }),
  white: new THREE.MeshLambertMaterial({ color: 0xfafafa }),
  skin: new THREE.MeshLambertMaterial({ color: 0xe8b87a }),
  hoodie: new THREE.MeshLambertMaterial({ color: 0x3a4050 }),
  pants: new THREE.MeshLambertMaterial({ color: 0x2a2a3a }),
  hair: new THREE.MeshLambertMaterial({ color: 0x1a1a1a }),
  // new peripherals
  keyboard: new THREE.MeshLambertMaterial({ color: 0xf0f0f0 }),
  keycap: new THREE.MeshLambertMaterial({ color: 0xe0e0e0 }),
  mousepad: new THREE.MeshLambertMaterial({ color: 0x111111 }),
  mouseMat: new THREE.MeshLambertMaterial({ color: 0xf5f5f5 }),
  piano: new THREE.MeshLambertMaterial({ color: 0x111116 }),
  pianoKeyWhite: new THREE.MeshLambertMaterial({ color: 0xf4f1e8 }),
  pianoKeyBlack: new THREE.MeshLambertMaterial({ color: 0x050505 }),
  windowFrame: new THREE.MeshLambertMaterial({ color: 0xd0c8b8 }),
  windowGlass: new THREE.MeshLambertMaterial({ color: 0x73b7f2, transparent: true, opacity: 0.42, emissive: 0x1d5f9f, emissiveIntensity: 0.12 }),
};
